apiVersion: v1
kind: Service
metadata:
  name: bind9-manager-service
spec:
  selector:
    app: bind9-manager-service
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-control
      port: 953
      targetPort: 953
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9-manager-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind9-manager-service
  template:
    metadata:
      labels:
        app: bind9-manager-service
    spec:
      containers:
        - name: bind9-manager
          image: legendzzzaioi/bind9-manager-service:v1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-control
              containerPort: 953
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "800m"
              memory: "1000Mi"